/**
 * SYNTHESIS SCREEN - Display mega synthesis with encrypted reveal
 *
 * Shows the 600-1500 word mega synthesis generated from:
 * - All cards + positions
 * - MCQ answers (cognitive dissonance, emotional patterns)
 * - MBTI type + communication style
 * - Advanced astrology (Lilith, Chiron, Nodes)
 * - Pop culture quotes
 * - Balanced Wisdom (Middle Way)
 */

import React, { useRef, useState } from 'react';
import {
  View,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  SafeAreaView,
  TextInput,
  Alert,
  Modal,
  Share,
  Clipboard,
  Linking,
  Platform,
} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import CyberpunkHeader from '../components/CyberpunkHeader';
import { NeonText, LPMUDText } from '../components/TerminalEffects';
import { NEON_COLORS } from '../styles/cyberpunkColors';
import { FeatureGate } from '../utils/featureGate';

const READINGS_KEY = '@lunatiq_saved_readings';
const MAX_READINGS = 20;

export default function SynthesisScreen({ route, navigation }) {
  const {
    synthesis,
    cards,
    intention,
    readingType,
    spreadType,
    readingId, // If viewing existing reading
    readingName, // If viewing existing reading
  } = route.params || {};

  const scrollViewRef = useRef(null);
  const [showSaveDialog, setShowSaveDialog] = useState(false);
  const [saveName, setSaveName] = useState('');
  const [isSaved, setIsSaved] = useState(!!readingId);

  const handleFinish = () => {
    if (!isSaved && !showSaveDialog) {
      // Prompt to save before leaving
      Alert.alert(
        'Save Reading?',
        'Would you like to save this reading for later?',
        [
          { text: 'Discard', onPress: () => navigation.navigate('Welcome'), style: 'destructive' },
          { text: 'Save', onPress: () => setShowSaveDialog(true) },
        ]
      );
    } else {
      navigation.navigate('Welcome');
    }
  };

  const handleSaveReading = () => {
    // Check permission
    if (!FeatureGate.canSaveReading()) {
      showUpgradePrompt('Save Readings');
      return;
    }

    if (!isSaved) {
      // Generate default name
      const defaultName = `${readingType || 'General'} Reading - ${new Date().toLocaleDateString()}`;
      setSaveName(defaultName);
      setShowSaveDialog(true);
    }
  };

  const handleShareReading = async () => {
    // Check permission
    if (!FeatureGate.canShareReading()) {
      showUpgradePrompt('Share Readings');
      return;
    }

    // Format reading for sharing
    const shareText = formatReadingForExport();

    try {
      const result = await Share.share({
        message: shareText,
        title: 'My Tarot Reading',
      });

      if (result.action === Share.sharedAction) {
        console.log('Reading shared successfully');
      }
    } catch (error) {
      console.error('Error sharing reading:', error);
      Alert.alert('Error', 'Failed to share reading. Please try again.');
    }
  };

  const handleCopyReading = () => {
    // Check permission
    if (!FeatureGate.canShareReading()) {
      showUpgradePrompt('Copy Readings');
      return;
    }

    const shareText = formatReadingForExport();
    Clipboard.setString(shareText);

    Alert.alert('Copied!', 'Reading copied to clipboard.', [{ text: 'OK' }]);
  };

  const formatReadingForExport = () => {
    const date = new Date().toLocaleDateString();
    let text = `━━━━━━━━━━━━━━━━━━━━━━━━\n`;
    text += `✨ LUNATIQ TAROT READING ✨\n`;
    text += `━━━━━━━━━━━━━━━━━━━━━━━━\n\n`;

    if (intention) {
      text += `🎯 INTENTION:\n${intention}\n\n`;
    }

    text += `📅 Date: ${date}\n`;
    text += `📊 Type: ${readingType || 'General'}\n`;
    text += `🃏 Spread: ${spreadType || 'Unknown'}\n`;
    text += `🔢 Cards: ${cards?.length || 0}\n\n`;

    text += `━━━━━━━━━━━━━━━━━━━━━━━━\n`;
    text += `💫 SYNTHESIS\n`;
    text += `━━━━━━━━━━━━━━━━━━━━━━━━\n\n`;
    text += `${synthesis}\n\n`;

    text += `━━━━━━━━━━━━━━━━━━━━━━━━\n`;
    text += `Generated by LunatIQ Tarot\n`;
    text += `Quantum randomness • Personalized insights\n`;
    text += `━━━━━━━━━━━━━━━━━━━━━━━━\n`;

    return text;
  };

  const showUpgradePrompt = (featureName) => {
    const price = FeatureGate.getUpgradePrice();
    const upgradeUrl = FeatureGate.getUpgradeUrl();

    Alert.alert(
      `🔒 Premium Feature`,
      `${featureName} is only available in the Premium version.\n\nUpgrade to Premium for ${price} to unlock:\n\n• Unlimited readings\n• Save reading history\n• Share & export readings\n• All spread types\n• Advanced interpretations\n• No ads, ever`,
      [
        { text: 'Maybe Later', style: 'cancel' },
        {
          text: `Upgrade for ${price}`,
          onPress: () => {
            if (upgradeUrl) {
              Linking.openURL(upgradeUrl);
            } else {
              Alert.alert('Coming Soon', 'Premium upgrade will be available soon!');
            }
          },
        },
      ]
    );
  };

  const saveReadingToStorage = async () => {
    try {
      // Load existing readings
      const data = await AsyncStorage.getItem(READINGS_KEY);
      let readings = data ? JSON.parse(data) : [];

      // Create reading object
      const reading = {
        id: readingId || `reading_${Date.now()}`,
        name: saveName.trim() || `Reading ${new Date().toLocaleDateString()}`,
        synthesis,
        cards,
        intention,
        readingType,
        spreadType,
        timestamp: new Date().toISOString(),
      };

      // If updating existing
      if (readingId) {
        readings = readings.map(r => r.id === readingId ? reading : r);
      } else {
        // Add new reading
        readings.unshift(reading); // Add to beginning

        // Limit to MAX_READINGS
        if (readings.length > MAX_READINGS) {
          readings = readings.slice(0, MAX_READINGS);
          Alert.alert(
            'Storage Limit',
            `Only the ${MAX_READINGS} most recent readings are kept. The oldest reading was removed.`
          );
        }
      }

      await AsyncStorage.setItem(READINGS_KEY, JSON.stringify(readings));
      console.log('Reading saved successfully:', reading.name);

      setShowSaveDialog(false);
      setIsSaved(true);

      Alert.alert(
        'Saved!',
        `"${reading.name}" has been saved to your reading history.`,
        [{ text: 'OK' }]
      );
    } catch (error) {
      console.error('Error saving reading:', error);
      Alert.alert('Error', 'Failed to save reading. Please try again.');
    }
  };

  return (
    <View style={styles.container}>
      <SafeAreaView style={styles.safeArea}>
        {/* Compact header */}
        <CyberpunkHeader compact={true} />

        {/* Title section */}
        <View style={styles.titleSection}>
          <LPMUDText style={styles.title}>
            $HIM${'>'} $HIY$SYNTHESIS$NOR$ $HIM${'<'}$NOR$
          </LPMUDText>
          <NeonText color={NEON_COLORS.dimCyan} style={styles.subtitle}>
            Your personalized reading
          </NeonText>
          {intention && (
            <View style={styles.intentionBox}>
              <LPMUDText style={styles.intentionText}>
                $HIY$INTENTION:$NOR$ {intention}
              </LPMUDText>
            </View>
          )}
        </View>

        {/* Scrollable synthesis */}
        <ScrollView
          ref={scrollViewRef}
          style={styles.scrollView}
          contentContainerStyle={styles.scrollContent}
          showsVerticalScrollIndicator={true}
        >
          <View style={styles.synthesisContainer}>
            <NeonText color={NEON_COLORS.hiWhite} style={styles.synthesisText}>
              {synthesis}
            </NeonText>
          </View>

          {/* Reading metadata */}
          <View style={styles.metadataBox}>
            <LPMUDText style={styles.metadataText}>
              $HIC$READING DETAILS$NOR${'\n'}
              $NOR$Type: {readingType || 'General'}$NOR${'\n'}
              $NOR$Spread: {spreadType || 'Unknown'}$NOR${'\n'}
              $NOR$Cards: {cards?.length || 0}$NOR$
            </LPMUDText>
          </View>
        </ScrollView>

        {/* Footer buttons */}
        <View style={styles.footer}>
          <TouchableOpacity onPress={handleSaveReading} style={styles.saveButton}>
            <LPMUDText style={styles.saveButtonText}>
              $HIY${'[ '} SAVE $NOR${' ]'}$NOR$
            </LPMUDText>
          </TouchableOpacity>

          <TouchableOpacity onPress={handleShareReading} style={styles.shareButton}>
            <LPMUDText style={styles.shareButtonText}>
              $HIC${'[ '} SHARE $NOR${' ]'}$NOR$
            </LPMUDText>
          </TouchableOpacity>

          <TouchableOpacity onPress={handleFinish} style={styles.finishButton}>
            <LPMUDText style={styles.finishButtonText}>
              $HIG${'[ '} DONE $NOR${' ]'}$NOR$
            </LPMUDText>
          </TouchableOpacity>
        </View>

        {/* Save Dialog Modal */}
        <Modal
          visible={showSaveDialog}
          transparent={true}
          animationType="fade"
          onRequestClose={() => setShowSaveDialog(false)}
        >
          <View style={styles.modalOverlay}>
            <View style={styles.modalContent}>
              <LPMUDText style={styles.modalTitle}>
                $HIC$SAVE READING$NOR$
              </LPMUDText>
              <NeonText color={NEON_COLORS.dimCyan} style={styles.modalSubtitle}>
                Give your reading a name:
              </NeonText>
              <TextInput
                style={styles.modalInput}
                value={saveName}
                onChangeText={setSaveName}
                placeholder={`${readingType || 'General'} Reading - ${new Date().toLocaleDateString()}`}
                placeholderTextColor={NEON_COLORS.dimCyan}
                maxLength={50}
                autoFocus
              />
              <View style={styles.modalButtons}>
                <TouchableOpacity
                  onPress={() => setShowSaveDialog(false)}
                  style={styles.modalCancelButton}
                >
                  <LPMUDText style={styles.modalCancelText}>
                    $HIR$CANCEL$NOR$
                  </LPMUDText>
                </TouchableOpacity>
                <TouchableOpacity
                  onPress={saveReadingToStorage}
                  style={styles.modalSaveButton}
                >
                  <LPMUDText style={styles.modalSaveText}>
                    $HIG$SAVE$NOR$
                  </LPMUDText>
                </TouchableOpacity>
              </View>
            </View>
          </View>
        </Modal>
      </SafeAreaView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000',
  },
  safeArea: {
    flex: 1,
  },
  titleSection: {
    padding: 20,
    paddingBottom: 12,
    borderBottomWidth: 2,
    borderBottomColor: NEON_COLORS.dimCyan,
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
  },
  title: {
    fontSize: 24,
    fontFamily: 'monospace',
    fontWeight: 'bold',
    marginBottom: 5,
    textAlign: 'center',
    lineHeight: 30,
  },
  subtitle: {
    fontSize: 12,
    fontFamily: 'monospace',
    textAlign: 'center',
    marginBottom: 12,
  },
  intentionBox: {
    borderWidth: 1,
    borderColor: NEON_COLORS.dimYellow,
    padding: 10,
    marginTop: 10,
    backgroundColor: 'rgba(10, 10, 0, 0.8)',
  },
  intentionText: {
    fontSize: 11,
    fontFamily: 'monospace',
    lineHeight: 16,
    textAlign: 'center',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 40,
  },
  synthesisContainer: {
    borderWidth: 2,
    borderColor: NEON_COLORS.hiCyan,
    padding: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.95)',
    marginBottom: 20,
  },
  synthesisText: {
    fontSize: 14,
    lineHeight: 22,
    fontFamily: 'monospace',
  },
  metadataBox: {
    borderWidth: 1,
    borderColor: NEON_COLORS.dimCyan,
    padding: 15,
    backgroundColor: 'rgba(0, 10, 10, 0.8)',
    marginTop: 10,
  },
  metadataText: {
    fontSize: 10,
    fontFamily: 'monospace',
    lineHeight: 16,
  },
  footer: {
    flexDirection: 'row',
    padding: 16,
    gap: 12,
    borderTopWidth: 2,
    borderTopColor: NEON_COLORS.dimCyan,
    backgroundColor: 'rgba(0, 0, 0, 0.95)',
  },
  saveButton: {
    flex: 1,
    padding: 16,
    borderWidth: 2,
    borderColor: NEON_COLORS.dimYellow,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    alignItems: 'center',
  },
  saveButtonText: {
    fontSize: 14,
    fontFamily: 'monospace',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  shareButton: {
    flex: 1,
    padding: 16,
    borderWidth: 2,
    borderColor: NEON_COLORS.dimCyan,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    alignItems: 'center',
  },
  shareButtonText: {
    fontSize: 14,
    fontFamily: 'monospace',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  finishButton: {
    flex: 1,
    padding: 16,
    borderWidth: 2,
    borderColor: NEON_COLORS.hiGreen,
    backgroundColor: 'rgba(0, 26, 0, 0.8)',
    alignItems: 'center',
  },
  finishButtonText: {
    fontSize: 16,
    fontFamily: 'monospace',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    width: '100%',
    maxWidth: 400,
    backgroundColor: '#000000',
    borderWidth: 2,
    borderColor: NEON_COLORS.hiCyan,
    padding: 24,
  },
  modalTitle: {
    fontSize: 20,
    fontFamily: 'monospace',
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 12,
  },
  modalSubtitle: {
    fontSize: 12,
    fontFamily: 'monospace',
    textAlign: 'center',
    marginBottom: 16,
  },
  modalInput: {
    borderWidth: 2,
    borderColor: NEON_COLORS.hiCyan,
    backgroundColor: 'rgba(0, 255, 255, 0.1)',
    padding: 12,
    fontSize: 14,
    fontFamily: 'monospace',
    color: NEON_COLORS.hiWhite,
    marginBottom: 20,
  },
  modalButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  modalCancelButton: {
    flex: 1,
    padding: 12,
    borderWidth: 2,
    borderColor: NEON_COLORS.dimRed,
    backgroundColor: 'rgba(255, 0, 0, 0.1)',
    alignItems: 'center',
  },
  modalCancelText: {
    fontSize: 14,
    fontFamily: 'monospace',
    fontWeight: 'bold',
  },
  modalSaveButton: {
    flex: 1,
    padding: 12,
    borderWidth: 2,
    borderColor: NEON_COLORS.hiGreen,
    backgroundColor: 'rgba(0, 255, 0, 0.1)',
    alignItems: 'center',
  },
  modalSaveText: {
    fontSize: 14,
    fontFamily: 'monospace',
    fontWeight: 'bold',
  },
});
